### ISSUE TITLE
Bug: HDRP 10.2.2 could not compile shader

### ISSUE THREAD

**Issue by krisrok** [Bajtix/CC0Textures-Unity-Import#3]
Updated to 10.3.1 and it works. Makes me wonder if it's actually compatible with 2019.4 ?

**Comment by bajtix** [comment]
This is using the built-in shader.. So there is no way it couldn't compile. The only issue may be that there is a URP shader graph which fails to compile, but the program should work. It detects HDRP if you have the HDRP asset set in the graphics settings, so maybe an issue occured there. I will try to resolve it and double check it, but I hope to resolve most of the issues until tommorow.

**Comment by krisrok** [comment]
Yes I think it was the URP shader.

**Comment by bajtix** [comment]
The URP one is not supposed to run on HDRP. I have no idea how to handle it, so the best solution would be to just delete it if it is not needed. I'll try and make a better solution to it someday, but this isn't really a major issue.
