### ISSUE TITLE
Bug: Maskmap does not get applied

### ISSUE THREAD

**Issue by krisrok** [Bajtix/CC0Textures-Unity-Import#4]
Generated materials end up without the mask map.

**Comment by bajtix** [comment]
What Unity and HDRP version are you using?

**Comment by krisrok** [comment]
2020.2.3 with HDRP 10.3.1

**Comment by bajtix** [comment]
I managed to fix it, for some reason it works only in some versions but it looks like the AssetDatabase.Refresh is always required. I hope to publish all the changes today or tommorow.

**Comment by krisrok** [comment]
Ah great. But I have some more :)

**Comment by bajtix** [comment]
You mean more bugs? Please post them here

**Comment by bajtix** [comment]
The newest release should fix this issue so I'll close it, in case anything doesn't work please reopen it, because I did not manage to test it well.
