### ISSUE TITLE
Bug: Previews do not load

### ISSUE THREAD

**Issue by krisrok** [Bajtix/CC0Textures-Unity-Import#5]
They end up loading a 404 page because the API sends the wrong urls.

They are missing a slash: 
https://cdn3.struffelproductions.com/file/CC0-Texturesmedia/sphere/512-JPG/PavingStones092_PREVIEW.jpg

and should be
https://cdn3.struffelproductions.com/file/CC0-Textures/media/sphere/512-JPG/PavingStones092_PREVIEW.jpg

 Not your fault really :) I wrote to cc0textures.com, hopefully they'll fix it anytime soon.

**Comment by Bajtix** [comment]
they must have updated the API, I will try to resolve all the issues today but there might have been a bigger change somewhere which is causing it all to break.

**Comment by bajtix** [comment]
Looks like they've fixed it
