### ISSUE TITLE
Enable displacement when there is a heightmap

### ISSUE THREAD

**Issue by krisrok** [Bajtix/CC0Textures-Unity-Import#8]
Right now you end up with a material without any displacement even if there is a heightmap present.

In my opinion you should enable displacement and leave it to the user to opt-out of using it.

Here's some snippet to spare you the quirks i had to go through:
```
if (hasHeightmap)
{
    previewMat.EnableKeyword("_DISPLACEMENT_LOCK_TILING_SCALE");
    previewMat.EnableKeyword("_HEIGHTMAP");
    previewMat.EnableKeyword("_PIXEL_DISPLACEMENT");
    previewMat.EnableKeyword("_PIXEL_DISPLACEMENT_LOCK_OBJECT_SCALE");

    previewMat.SetFloat("_DisplacementMode", 2);

    previewMat.SetTexture("_HeightMap", heightMapTexture);
}
``` 
This enables the pixel displacement mode on the HDRP/Lit shader.

**Comment by krisrok** [comment]
Sorry, labeled as 'bug' by accident I don't know how to remove the label.

**Comment by bajtix** [comment]
You are probably right about the fact that the heightmap should be enabled by default, it's just that I'm not sure if all versions of HDRP handle it the same way. I wanted to make the user choose if they want vertex or pixel displacement, but I'll take a look and hopefully change it.

**Comment by bajtix** [comment]
This should work in the new (pre)release. If it does not, please reopen the issue.
